### ISSUE TITLE
Thanks! Just a note

### ISSUE THREAD

**Issue by Kalimaha** [hmsk/netlify-functions-in-go#1]
Hey, thanks so much for this repo. I'm working on a little dashboard as a side project but I got stuck when I wanted to add a second function, and your repo came really handy.

Just a little note: when I tried to put my utils in `internal/pkg/utils` and then import them, as you suggests:

https://github.com/hmsk/netlify-functions-in-go/blob/f6d161c2de86005938a4c3a58fa7e894ed707157/cmd/hello/main.go#L8

I got the `use of internal package not allowed` Go error when i tried to build it in Netlify. It seems it's a Go thing, and I just moved my stuff into `pkg/utils` rather than `internal/pkg/utils` and everything works 🙂

**Comment by hmsk** [comment]
Great to hear! I didn't think anyone uses this template actually.

hmm, my project is working well as is 🤔 
I guess you might need to edit netlify.toml to follow your project https://github.com/hmsk/netlify-functions-in-go/blob/master/netlify.toml#L8

**Comment by Kalimaha** [comment]
> Great to hear! I didn't think anyone uses this template actually.
> 
> 
> 
> hmm, my project is working well as is 🤔 
> 
> I guess you might need to edit netlify.toml to follow your project https://github.com/hmsk/netlify-functions-in-go/blob/master/netlify.toml#L8

Oh I have that as well https://github.com/Kalimaha/devops-dashboard/blob/master/netlify.toml. But, anyways, all good, thanks again for unblocking me with multiple Go functions in the same repo 🙂

**Comment by hmsk** [comment]
Thanks 😉 but I was just curious about why you needed to tweak that.
And I found out the suspicious point. It's my private Netlify function's `netlify.toml`:

![image](https://user-images.githubusercontent.com/85887/89755581-c696ad80-da94-11ea-9f1e-ad4ea96fe50c.png)

`GO_IMPORT_PATH` is placed under the `[build.environment]`, but your project specifies `[template.environment]` as same as my template project shows.
This `[template.environment]` should be replaced when you initiate your repository with Netlify deploy button, but if it's skipped, `[template.environment]` block remains somehow. I may look into the way to avoid such a situation.

Just FYI, and now I close this issue. Thanks again!

**Comment by hmsk** [comment]
Ah, [`[template.environment]` provides the text input when we deploy with Netlify button](https://docs.netlify.com/site-deploys/create-deploys/#template-configuration).
The input should give environment variable for deploy setting on:

![image](https://user-images.githubusercontent.com/85887/89756818-67d33300-da98-11ea-9b2a-a6f92ab43033.png)

Thus, `GO_IMPORT_PATH` on your environment setting should say `github.com/Kalimaha/devops-dashboard` or `netlify.toml` has `GO_IMPORT_PATH="github.com/Kalimaha/devops-dashboard"` on `[build.environment]` section.
